language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy # zip 에 포함시킬 파일을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-depoly * # before-deploy 로 이동 후 전체 압축
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/shareyourtrip.zip

deploy :
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis Environment Variables
    secret_access_key: $AWS_SECRET_KEY # Travis Environment Variables
    bucket: shareyourtrip-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근 private
    local_dir: deploy # before deploy 에 설정한 디렉토리
    wait-until-deploed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis Environment Variables
    secret_access_key: $AWS_SECRET_KEY # Travis Environment Variables

    bucket: shareyourtrip-springboot-build
    key: shareyourtrip.zip

    bundle_type: zip
    application: shareyourtrip-codedeploy

    deployment_group: shareyourtrip-group

    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일 알림
notifications:
  email:
    recipients:
      - jbb9229@gmail.com