version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/step3/zip
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh # Nginx 와 연결되어 있지 않은 Application 종료
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh # Nginx 와 연결되어 있지 않은 Port로 새버전의 Application 시작
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # 새 Application이 정상적으로 실행됐는지 확인
      timeout: 60
      runas: ec2-user